### ISSUE TITLE
Yandex antivirus "Manul" founded virus codes in your files.

### ISSUE THREAD

**Issue by antoncom** [kartik-v/mpdf#6]
Found virus {HEX}php.exe.globals.402.UNOFFICIAL in /mpdf60/1/mpdf60/examples/example61_new_mPDF_v6-
0_features.php
Found virus {HEX}php.exe.globals.402.UNOFFICIAL in 
/mpdf60/examples/example61_new_mPDF_v6-0_features.php
![yandex_036](https://cloud.githubusercontent.com/assets/6522104/11175939/fcc17542-8c48-11e5-9f58-6c8e163c357b.png)

**Comment by danielhjames** [comment]
Please take a look at the source of https://github.com/kartik-v/mpdf/blob/master/examples/example61_new_mPDF_v6-0_features.php and compare it to the file on your machine. I see no Windows executable there.

If the virus report is accurate, it may be because the virus got on your system independently of downloading mPDF.

**Comment by antoncom** [comment]
The issue got from hosting provider. The pointed file is located on Linux-based web server. If I scan the file by Yandex antivirus ("Manul") it generates that notification. Yellow status means that antivirus consideres it as suspicious code. Probably, it is not dangerous. I just wanted you to be inforemd. Thank you for your mpdf.
